addCharacterInput:
  type: input-object
  config:
    fields:
      name:
        type: "String"
        #validation: # applying constraints to `username`
        #    - Length:
        #        min: 0
        #        max: 32
      description:
        type: "String"