Character:
  type: object
  #todo: ver depois interfaces: [CharacterInterface] # multiple interfaces allowed
  config:
    description: "Some character from a movie"
    fields:
      id:
        type: "ID"
        description: "The ID"
      name:
        type: "String"
      movies:
        type: Movies