Mutation:
  type: object
  config:
    fields:
      addCharacter:
        type: addCharacterPayload!
        resolve: "@=mutation('add_character', args['input']['name'])"
        args:
          #using input object type is optional, we use it here to be iso with relay mutation example.
          input:
            type: addCharacterInput!