Query:
  type: object
  config:
    fields:
      characters:
        type: "[Character]"
        args:
          name:
            type: "String"
        resolve: '@=query("App\\GraphQL\\Resolver\\CharacterResolver::get", args["name"])'